apiVersion: v1
kind: ConfigMap
metadata:
  name: commercehub-config
  namespace: commercehub
  labels:
    app.kubernetes.io/part-of: commercehub
data:
  DB_URL: jdbc:oracle:thin:@//__INFRA_HOST__:1521/FREEPDB1
  JWT_ISSUER: https://commercehub.example/issuer
  JWT_LIFESPAN_SECONDS: "3600"
  PRODUCT_SERVICE_URL: http://product-service:8080
  KAFKA_BOOTSTRAP_SERVERS: __INFRA_HOST__:39092
  OTEL_EXPORTER_OTLP_ENDPOINT: http://__INFRA_HOST__:4317
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  FLYWAY_MIGRATE_AT_START: "false"
