apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: commercehub
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/part-of: commercehub
    app.kubernetes.io/version: "0.7.0"
spec:
  selector:
    app.kubernetes.io/name: product-service
  ports:
    - name: http
      port: 8080
      targetPort: http
