apiVersion: batch/v1
kind: Job
metadata:
  name: user-service-migrate
  namespace: commercehub
  labels:
    app.kubernetes.io/name: user-service
    app.kubernetes.io/part-of: commercehub
    app.kubernetes.io/version: "0.8.0"
    app.kubernetes.io/component: migrate
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 3
  ttlSecondsAfterFinished: 600
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        app.kubernetes.io/name: user-service
        app.kubernetes.io/part-of: commercehub
        app.kubernetes.io/version: "0.8.0"
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: ghcr.io/local/commercehub-user-service:0.8.0
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: commercehub-config
            - configMapRef:
                name: commercehub-runtime
          env:
            - name: FLYWAY_MIGRATE_AT_START
              value: "true"
            - name: COMMERCEHUB_MIGRATE_ONLY
              value: "true"
            - name: USER_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commercehub-secrets
                  key: USER_DB_PASSWORD
            - name: DEMO_ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: commercehub-secrets
                  key: DEMO_ADMIN_EMAIL
            - name: DEMO_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: commercehub-secrets
                  key: DEMO_ADMIN_PASSWORD
            - name: DEMO_ADMIN_FULL_NAME
              valueFrom:
                secretKeyRef:
                  name: commercehub-secrets
                  key: DEMO_ADMIN_FULL_NAME
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 768Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
